### ISSUE TITLE
[AVM Module Issue]: Adding a for_each to the root file

### ISSUE THREAD

**Issue by cshea-msft** [Azure/terraform-azurerm-avm-res-network-publicipaddress#55]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Can we add the for_each to the public_ip in the root? There might be scenarios when a user might need to create multiple PIPs for their module.

**Comment by cshea-msft** [comment]
azure firewall best practice is to have at least two-four pips assigned. if its easier to do a for_each in the actually deployment code that is fine thought i would just add the feedback to get thoughts.

**Comment by matt-FFFFFF** [comment]
Can't we do a for each on the module instead?

Resource modules must only deploy one of the primary resource
